name: Build and Package BewerberPDFApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]  # Verwende Python 3.9 für bessere Kompatibilität
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python ${{ matrix.python-version }} einrichten
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip updaten und Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller img2pdf pandas openpyxl numpy
          # Falls du weitere Pakete in requirements.txt hast:
          # pip install -r requirements.txt

      - name: Build Executable mit PyInstaller
        run: |
          # Falls dein Skript anders heißt, passe den Namen an.
          pyinstaller --clean --onefile --name BewerberPDFApp dein_script.py

      - name: Build-Artefakt hochladen
        uses: actions/upload-artifact@v3
        with:
          name: BewerberPDFApp
          path: dist/BewerberPDFApp
