name: Build macOS Universal App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Verwendet x86_64-Architektur (Intel)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app

    - name: Build macOS Universal App
      run: |
        export ARCHFLAGS="-arch x86_64 -arch arm64"  # Erstellt Universal2-Binaries
        python setup.py py2app

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Universal-App
        path: dist
