name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Aktualisiert auf die neueste Version

    - name: Set up Python
      uses: actions/setup-python@v5  # Aktualisiert auf die neueste Version
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app

    - name: Build macOS App
      run: |
        python setup.py py2app

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Aktualisiert auf die neueste Version
      with:
        name: macOS-App
        path: dist
