name: Build Arm64 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # ARM64-Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pillow pillow-heif reportlab openpyxl pyinstaller numpy

      - name: Create numpy hook
        run: |
          echo "from PyInstaller.utils.hooks import collect_data_files" > hook-numpy.py
          echo "datas = collect_data_files('numpy')" >> hook-numpy.py

      - name: Build App
        run: |
          pyinstaller --onefile --windowed --name BewerberPDFApp --target-arch arm64 --additional-hooks-dir=. test.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BewerberPDFApp
          path: dist/
