name: Build macOS Universal App with PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Verwendet macOS Runner (x86_64 oder ARM64)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Verwende die Python-Version, die dein Skript benötigt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS Universal App
      run: |
        # Erstelle eine Universal2-Binary (x86_64 + ARM64)
        pyinstaller --name=BewerberPDFs --windowed --onefile --clean \
                    --target-arch universal2 bewerber_pdfs.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BewerberPDFs-macOS-App
        path: dist/
