name: Build ARM64 App

on:
  push:
    branches:
      - main  # Trigger den Workflow bei einem Push auf den main-Branch
  pull_request:
    branches:
      - main  # Trigger den Workflow bei einem Pull Request auf den main-Branch

jobs:
  build:
    runs-on: macos-arm64  # Verwende einen ARM64-Runner

    steps:
      # Schritt 1: Checkout des Repositorys
      - name: Checkout code
        uses: actions/checkout@v3

      # Schritt 2: Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Verwende Python 3.12

      # Schritt 3: Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas img2pdf pyinstaller

      # Schritt 4: App mit PyInstaller erstellen
      - name: Build App
        run: |
          pyinstaller --onefile --windowed --name BewerberPDFApp --target-arch arm64 IhrSkript.py

      # Schritt 5: Artefakte speichern
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BewerberPDFApp
          path: dist/
