name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Wir verwenden macOS-Runner für die Erstellung der .app-Datei

    steps:
    # Checkout der Repository-Dateien
    - name: Checkout repository
      uses: actions/checkout@v3  # Update auf Version 3

    # Installiere Python und Abhängigkeiten
    - name: Set up Python
      uses: actions/setup-python@v3  # Update auf Version 3
      with:
        python-version: '3.9'  # Stelle sicher, dass die Python-Version übereinstimmt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Falls du ein requirements.txt hast
        pip install pyinstaller  # Installiere PyInstaller, falls noch nicht installiert

    # Erstelle die .app-Datei für beide Architekturen
    - name: Build macOS app for both architectures
      run: |
        pyinstaller --onefile --windowed --name "MyApp" --distpath ./dist --workpath ./build --target-architecture=arm64,x86_64 your_script.py  # Ändere 'your_script.py' auf den Namen deiner Python-Datei

    # Archive das Ergebnis als Artefakt
    - name: Archive .app file
      uses: actions/upload-artifact@v3  # Update auf Version 3
      with:
        name: macos-app
        path: ./dist/MyApp.app  # Der Pfad zur erstellten .app-Datei
