name: Build Universal2 App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Verwende einen x86_64 Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas img2pdf pyinstaller

      - name: Build App
        run: |
          pyinstaller --onefile --windowed --name BewerberPDFApp --target-arch universal2 test.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BewerberPDFApp
          path: dist/
