name: Build ARM64 App

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: macos-14  # Nutzt macOS 14 (x86_64 mit Rosetta)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM64 Python
        run: |
          arch -arm64 brew install python

      - name: Install dependencies for ARM64
        run: |
          arch -arm64 python3 -m pip install --upgrade pip
          arch -arm64 pip3 install --no-binary :all: pandas img2pdf pyinstaller

      - name: Build ARM64 App
        run: |
          arch -arm64 pyinstaller --onefile --windowed --name BewerberPDFApp test.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BewerberPDFApp
          path: dist/
