name: Build macOS App for x86_64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Verwendet macOS Runner (x86_64)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # Verwende die Python-Version, die dein Skript benötigt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS App for x86_64
      run: |
        # Setze die Zielarchitektur auf x86_64
        export ARCHFLAGS="-arch x86_64"
        # Erstelle die App mit PyInstaller
        pyinstaller --name=BewerberPDFs --windowed --onefile --clean bewerber_pdfs.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BewerberPDFs-macOS-x86_64
        path: dist/
